@extends('errors.layout')
@section('title','تعذر الوصول إلى الخادم')
@section('status','انقطاع اتصال')
@section('code','502')
@section('label','استجابة غير صالحة')
@section('heading','تعذر الاتصال بخدمة النظام')
@section('message','الخادم الأمامي يعمل، لكن خدمة التطبيق لم تستجب بالشكل المطلوب. غالبًا يكون الانقطاع مؤقتًا.')
@section('note','تحقق من تشغيل Apache وPHP وخدمة قاعدة البيانات، ثم استخدم زر إعادة المحاولة.')
