@extends('errors.layout')
@section('title','النظام غير متاح مؤقتًا')
@section('status','صيانة مؤقتة')
@section('code','503')
@section('label','الخدمة غير متاحة')
@section('heading','النظام تحت الصيانة')
@section('message','تم إيقاف النظام مؤقتًا لإجراء صيانة أو تحديث. سيعود للعمل فور اكتمال العملية.')
@section('note','لا تحتاج إلى تنفيذ أي إجراء. ستتم إعادة المحاولة تلقائيًا بعد ثوانٍ.')
