@extends('layouts.app')

@section('title', 'استيراد التعاميم والكتب المتفرقة القديمة')

@section('content')
<style>
.legacy-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.legacy-source{border:1px solid #334155;border-radius:14px;padding:14px;margin-bottom:12px;background:rgba(15,23,42,.34)}.legacy-source-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:10px}.legacy-source label{display:block;font-weight:700;margin-bottom:6px}.legacy-source input,.legacy-source select{width:100%}.legacy-note{padding:12px 14px;border:1px solid rgba(56,189,248,.35);border-radius:12px;background:rgba(14,116,144,.1);line-height:1.8}.legacy-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}@media(max-width:800px){.legacy-source-grid{grid-template-columns:1fr}}
</style>
<div class="page-header"><div><h1>استيراد التعاميم والكتب المتفرقة القديمة</h1><p>فحص المصادر ثم استيراد الملفات المختارة مع التحقق من الحجم وبصمة SHA-256.</p></div></div>
<div class="legacy-note mb-4">يبدأ العمل بفحص تجريبي. بعد مراجعة النتائج يمكن استيراد دفعات مختارة. النظام ينسخ الملفات إلى التخزين المحلي ولا ينقل أو يحذف الملفات الأصلية من Server-1.</div>
<div class="card mb-4"><div class="card-header"><h2>عملية فحص جديدة</h2></div><form method="POST" action="{{ route('legacy-circular-misc-import.store') }}" class="card-body">@csrf
<div class="form-group"><label>اسم العملية</label><input type="text" name="name" value="{{ old('name') }}" placeholder="مثال: فحص أرشيف التعاميم والمتفرقات 2026"></div>
<div id="sources"></div>
<div class="legacy-actions"><button type="button" class="btn btn-light" id="add-source">إضافة مصدر</button><button class="btn btn-primary" type="submit">بدء الفحص التجريبي</button></div>
</form></div>
<div class="card"><div class="card-header"><h2>عمليات الفحص السابقة</h2></div>
@if($runs->count())<div class="table-responsive"><table class="table"><thead><tr><th>#</th><th>الاسم</th><th>الفحص</th><th>الاستيراد</th><th>الإجمالي</th><th>الجاهز</th><th>المستورد</th><th>الفاشل</th><th>التاريخ</th><th>الإجراءات</th></tr></thead><tbody>
@foreach($runs as $run)<tr><td>{{ $run->id }}</td><td>{{ $run->name }}</td><td>{{ $run->status_name }}</td><td>{{ $run->import_status_name }}</td><td>{{ $run->total_files }}</td><td>{{ $run->ready_count + $run->needs_review_count }}</td><td>{{ $run->imported_files }}</td><td>{{ $run->import_failed_files }}</td><td>{{ optional($run->created_at)->format('Y-m-d H:i') }}</td><td><div class="legacy-actions"><a class="btn btn-sm btn-primary" href="{{ route('legacy-circular-misc-import.show',$run) }}">عرض ومراجعة</a><form method="POST" action="{{ route('legacy-circular-misc-import.destroy',$run) }}" onsubmit="return confirm('حذف تقرير الفحص فقط؟')">@csrf @method('DELETE')<button class="btn btn-sm btn-danger">حذف التقرير</button></form></div></td></tr>@endforeach
</tbody></table></div>{{ $runs->links() }}@else<p class="empty-state">لا توجد عمليات فحص سابقة.</p>@endif</div>
<template id="source-template"><div class="legacy-source" data-source><div class="legacy-source-grid"><div><label>مسار المجلد على Server-1</label><input type="text" data-name="source_path" placeholder="\\Server-1\المشاركة\التعاميم" required></div><div><label>الوحدة</label><select data-name="target_module" data-module required><option value="circular">التعاميم</option><option value="misc_book">الكتب المتفرقة</option></select></div><div><label>التصنيف</label><select data-name="category_id" data-category><option value="">بدون تصنيف</option></select></div></div><div class="legacy-source-grid mt-3"><div><label>الجهة الافتراضية</label><input type="text" data-name="default_entity" placeholder="اختياري"></div><div data-misc-only><label>الاتجاه الافتراضي</label><select data-name="default_direction"><option value="incoming">وارد</option><option value="outgoing">صادر</option><option value="internal">داخلي</option></select></div><div data-misc-only><label>الطبيعة الافتراضية</label><select data-name="default_nature"><option value="unspecified">غير محدد</option><option value="military">عسكري</option><option value="civil">مدني</option></select></div></div><div class="legacy-actions mt-3"><label><input type="checkbox" data-name="recursive" value="1" checked> فحص المجلدات الفرعية</label><button type="button" class="btn btn-sm btn-danger" data-remove>إزالة المصدر</button></div></div></template>
<script>
(() => { const circular=@json($circularCategories->map(fn($c)=>['id'=>$c->id,'name'=>$c->full_name])->values()); const misc=@json($miscCategories->map(fn($c)=>['id'=>$c->id,'name'=>$c->full_name])->values()); const box=document.getElementById('sources'); const tpl=document.getElementById('source-template');
function refresh(row){const module=row.querySelector('[data-module]').value; const list=module==='circular'?circular:misc; const select=row.querySelector('[data-category]'); const current=select.value; select.innerHTML='<option value="">بدون تصنيف</option>'+list.map(c=>`<option value="${c.id}">${c.name}</option>`).join(''); if([...select.options].some(o=>o.value===current))select.value=current; row.querySelectorAll('[data-misc-only]').forEach(el=>el.style.display=module==='misc_book'?'block':'none');}
function rename(){[...box.querySelectorAll('[data-source]')].forEach((row,i)=>row.querySelectorAll('[data-name]').forEach(el=>{el.name=`sources[${i}][${el.dataset.name}]`;}));}
function add(){const row=tpl.content.firstElementChild.cloneNode(true); box.appendChild(row); row.querySelector('[data-module]').addEventListener('change',()=>refresh(row)); row.querySelector('[data-remove]').addEventListener('click',()=>{row.remove(); if(!box.children.length)add(); rename();}); refresh(row); rename();}
document.getElementById('add-source').addEventListener('click',add); add(); })();
</script>
@endsection
