@extends('layouts.app')
@section('title','مراجعة واستيراد الأرشيف القديم')
@section('content')
<style>
.stat-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:12px}.stat-card{border:1px solid #334155;border-radius:13px;padding:14px;background:rgba(15,23,42,.35)}.stat-card strong{display:block;font-size:24px;margin-top:5px}.status-ready{color:#22c55e}.status-needs_review{color:#f59e0b}.status-existing{color:#38bdf8}.status-duplicate{color:#c084fc}.status-unreadable,.status-unsupported,.status-import_failed{color:#ef4444}.status-imported{color:#10b981}.path-cell{min-width:300px;white-space:normal;word-break:break-word}.filter-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.import-card{border:1px solid rgba(148,163,184,.35);border-radius:14px;padding:14px;margin:12px;background:rgba(15,23,42,.24)}.import-card-head{display:flex;gap:12px;justify-content:space-between;align-items:flex-start;flex-wrap:wrap}.import-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px;margin-top:12px}.import-grid label{display:block;font-weight:700;margin-bottom:5px}.import-grid input,.import-grid select,.import-grid textarea{width:100%}.import-grid textarea{min-height:72px}.import-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.source-note{font-size:12px;word-break:break-word;line-height:1.7}.confirmation-box{border:1px solid rgba(245,158,11,.45);background:rgba(245,158,11,.08);border-radius:14px;padding:14px;margin:14px}.confirmation-box input{max-width:420px}
</style>
<div class="page-header"><div><h1>{{ $run->name }}</h1><p>عملية رقم {{ $run->id }} — الفحص: {{ $run->status_name }} — الاستيراد: {{ $run->import_status_name }}</p></div><a class="btn btn-light" href="{{ route('legacy-circular-misc-import.index') }}">العودة</a></div>
@if($run->error_message)<div class="alert alert-danger">{{ $run->error_message }}</div>@endif
<div class="stat-grid mb-4"><div class="stat-card">الإجمالي<strong>{{ $run->total_files }}</strong></div><div class="stat-card">جاهز<strong class="status-ready">{{ $run->ready_count }}</strong></div><div class="stat-card">يحتاج مراجعة<strong class="status-needs_review">{{ $run->needs_review_count }}</strong></div><div class="stat-card">موجود<strong class="status-existing">{{ $run->existing_count }}</strong></div><div class="stat-card">مكرر<strong class="status-duplicate">{{ $run->duplicate_count }}</strong></div><div class="stat-card">مستورد<strong class="status-imported">{{ $run->imported_files }}</strong></div><div class="stat-card">فشل الاستيراد<strong class="status-import_failed">{{ $run->import_failed_files }}</strong></div><div class="stat-card">الحجم<strong>{{ \App\Models\CircularAttachment::formatBytes((int)$run->total_size) }}</strong></div></div>
<div class="card mb-4"><div class="card-header"><h2>المصادر</h2></div><div class="table-responsive"><table class="table"><thead><tr><th>المسار</th><th>الوحدة</th><th>التصنيف</th><th>فحص فرعي</th></tr></thead><tbody>@foreach($run->sources as $source)<tr><td class="path-cell">{{ $source->source_path }}</td><td>{{ $source->target_module==='circular'?'التعاميم':'الكتب المتفرقة' }}</td><td>{{ $source->category?->full_name ?: 'بدون تصنيف' }}</td><td>{{ $source->recursive?'نعم':'لا' }}</td></tr>@endforeach</tbody></table></div></div>
<div class="card mb-4"><div class="card-header"><h2>البحث والتصفية</h2></div><form method="GET" class="card-body"><div class="filter-grid"><input type="text" name="q" value="{{ $filters['q'] }}" placeholder="بحث بالاسم أو المسار أو الموضوع"><select name="status"><option value="all">كل الحالات</option>@foreach(['ready'=>'جاهز','needs_review'=>'يحتاج مراجعة','imported'=>'تم الاستيراد','import_failed'=>'فشل الاستيراد','existing'=>'موجود','duplicate'=>'مكرر','unreadable'=>'غير قابل للقراءة','unsupported'=>'غير مدعوم'] as $key=>$label)<option value="{{ $key }}" @selected($filters['status']===$key)>{{ $label }}</option>@endforeach</select><select name="target_module"><option value="all">كل الوحدات</option><option value="circular" @selected($filters['target_module']==='circular')>التعاميم</option><option value="misc_book" @selected($filters['target_module']==='misc_book')>الكتب المتفرقة</option></select><select name="source_id"><option value="">كل المصادر</option>@foreach($run->sources as $source)<option value="{{ $source->id }}" @selected((string)$filters['source_id']===(string)$source->id)>{{ \Illuminate\Support\Str::limit($source->source_path,50) }}</option>@endforeach</select></div><button class="btn btn-primary mt-3">تطبيق الفلاتر</button></form></div>

<form method="POST" action="{{ route('legacy-circular-misc-import.import',$run) }}" id="legacy-import-form">@csrf
<div class="card"><div class="card-header"><div><h2>مراجعة الملفات والاستيراد الفعلي</h2><p class="text-muted">عدّل البيانات عند الحاجة، ثم حدد الملفات المراد استيرادها.</p></div><div class="import-actions"><button type="button" class="btn btn-light" id="select-page">تحديد القابل للاستيراد في الصفحة</button><button type="button" class="btn btn-light" id="clear-page">إلغاء التحديد</button></div></div>
@forelse($items as $item)
<div class="import-card">
<div class="import-card-head"><div class="import-actions">@if($item->isImportable())<input type="checkbox" class="import-check" name="items[]" value="{{ $item->id }}" id="item-{{ $item->id }}"><label for="item-{{ $item->id }}"><strong>#{{ $item->id }} — {{ $item->module_name }}</strong></label>@else<strong>#{{ $item->id }} — {{ $item->module_name }}</strong>@endif <span class="status-{{ $item->status }}">{{ $item->status_name }}</span> <span>{{ $item->proposed_number ?: '-' }}</span></div><div>{{ $item->file_size_for_humans }}</div></div>
@if($item->status==='imported')<div class="alert alert-success mt-3">تم الاستيراد برقم <strong>{{ $item->proposed_number }}</strong>. @if($item->circular)<a href="{{ route('circulars.show',$item->circular) }}">فتح التعميم</a>@elseif($item->miscBook)<a href="{{ route('misc-books.show',$item->miscBook) }}">فتح الكتاب المتفرق</a>@endif</div>@elseif($item->status==='import_failed')<div class="alert alert-danger mt-3">{{ $item->import_error ?: $item->notes }}</div>@endif
@if($item->isImportable())
<div class="import-grid"><div><label>التاريخ</label><input type="date" name="dates[{{ $item->id }}]" value="{{ old('dates.'.$item->id,optional($item->proposed_date)->format('Y-m-d')) }}"></div><div><label>الرقم الأصلي</label><input type="text" name="original_numbers[{{ $item->id }}]" value="{{ old('original_numbers.'.$item->id,$item->proposed_original_number) }}"></div><div style="grid-column:span 2"><label>الموضوع</label><textarea name="subjects[{{ $item->id }}]">{{ old('subjects.'.$item->id,$item->proposed_subject) }}</textarea></div><div><label>التصنيف</label><select name="category_ids[{{ $item->id }}]"><option value="">اختر التصنيف</option>@php($categoryList=$item->target_module==='circular'?$circularCategories:$miscCategories)@foreach($categoryList as $category)<option value="{{ $category->id }}" @selected((string)old('category_ids.'.$item->id,$item->category_id)===(string)$category->id)>{{ $category->full_name }}</option>@endforeach</select></div><div><label>{{ $item->target_module==='circular'?'الجهة المصدرة':'الجهة الافتراضية' }}</label><input type="text" name="entities[{{ $item->id }}]" value="{{ old('entities.'.$item->id,$item->proposed_entity) }}"></div>
@if($item->target_module==='misc_book')<div><label>الاتجاه</label><select name="directions[{{ $item->id }}]"><option value="incoming" @selected(old('directions.'.$item->id,$item->proposed_direction ?: 'incoming')==='incoming')>وارد</option><option value="outgoing" @selected(old('directions.'.$item->id,$item->proposed_direction)==='outgoing')>صادر</option><option value="internal" @selected(old('directions.'.$item->id,$item->proposed_direction)==='internal')>داخلي</option></select></div><div><label>الطبيعة</label><select name="natures[{{ $item->id }}]"><option value="unspecified" @selected(old('natures.'.$item->id,$item->proposed_nature ?: 'unspecified')==='unspecified')>غير محدد</option><option value="military" @selected(old('natures.'.$item->id,$item->proposed_nature)==='military')>عسكري</option><option value="civil" @selected(old('natures.'.$item->id,$item->proposed_nature)==='civil')>مدني</option></select></div><div><label>الجهة المرسلة</label><input type="text" name="senders[{{ $item->id }}]" value="{{ old('senders.'.$item->id,($item->proposed_direction ?: 'incoming')==='incoming'?$item->proposed_entity:null) }}"></div><div><label>الجهة المستلمة</label><input type="text" name="receivers[{{ $item->id }}]" value="{{ old('receivers.'.$item->id,$item->proposed_direction==='outgoing'?$item->proposed_entity:null) }}"></div><div><label>اسم الموظف</label><input type="text" name="employee_names[{{ $item->id }}]" value="{{ old('employee_names.'.$item->id) }}"></div><div><label>اسم الهيئة</label><input type="text" name="authority_names[{{ $item->id }}]" value="{{ old('authority_names.'.$item->id) }}"></div>@endif</div>
@endif
<div class="source-note mt-3"><strong>{{ $item->file_name }}</strong><br>{{ $item->source_path }}<br>SHA-256: {{ $item->sha256 ?: '-' }}@if($item->notes)<br>ملاحظة: {{ $item->notes }}@endif</div>
</div>
@empty<div class="empty-state">لا توجد نتائج مطابقة.</div>@endforelse
<div class="px-3">{{ $items->links() }}</div></div>
@if($run->status==='completed')<div class="confirmation-box"><strong>تأكيد الاستيراد</strong><p>اكتب العبارة التالية كما هي: <code>استيراد التعاميم والمتفرقات</code></p><input type="text" name="confirmation_text" autocomplete="off" placeholder="استيراد التعاميم والمتفرقات"><div class="mt-3"><button type="submit" class="btn btn-primary">استيراد الملفات المحددة</button></div><p class="text-muted mt-3">يتم نسخ الملفات فقط. تبقى الملفات الأصلية على Server-1 دون تعديل أو حذف.</p></div>@endif
</form>
<div class="alert alert-info mt-4">الأرقام المقترحة أثناء الفحص إرشادية. الرقم النهائي يُحجز عند الاستيراد. التعاميم تستخدم تسلسل 2610000 والكتب المتفرقة 2620000 للسنة الحالية.</div>
<script>
(() => {const checks=[...document.querySelectorAll('.import-check')];document.getElementById('select-page')?.addEventListener('click',()=>checks.forEach(c=>c.checked=true));document.getElementById('clear-page')?.addEventListener('click',()=>checks.forEach(c=>c.checked=false));document.getElementById('legacy-import-form')?.addEventListener('submit',e=>{if(!checks.some(c=>c.checked)){e.preventDefault();alert('حدد ملفًا واحدًا على الأقل للاستيراد.');}});})();
</script>
@endsection
