@extends('layouts.app')

@section('title', 'استعادة نسخة احتياطية')

@section('content')
<div class="page-header backup-polish-v1">
    <div><h1>استعادة نسخة احتياطية</h1><p>راجع محتويات النسخة جيداً قبل تنفيذ الاستعادة. سيتم إنشاء نسخة أمان تلقائياً قبل أي عملية.</p></div>
    <div class="page-actions">@if(auth()->user()?->hasPermission('backups.view'))<a href="{{ route('backups.inspect', $fileName) }}" class="btn btn-info">فحص النسخة</a>@endif <a href="{{ route('backups.index') }}" class="btn btn-light">رجوع</a></div>
</div>
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="alert alert-danger restore-danger"><strong>تنبيه شديد الأهمية:</strong> الاستعادة ستستبدل البيانات أو الملفات الحالية حسب الخيار المحدد. لا تنفذها إلا بعد التأكد من النسخة وفهم أثر العملية.</div>
<div class="card restore-summary"><h3 dir="ltr">{{ $fileName }}</h3><div class="restore-stats-grid"><div class="stat-box"><span>نوع النسخة</span><strong>{{ $inferredType }}</strong></div><div class="stat-box"><span>حجم النسخة</span><strong>{{ $fileSize }}</strong></div><div class="stat-box"><span>ملفات SQL</span><strong>{{ count($sqlFiles) }}</strong></div><div class="stat-box"><span>ملفات المرفقات</span><strong>{{ $documentFilesCount }}</strong></div></div></div>
@if(count($warnings) > 0)<div class="alert alert-warning mt-3"><strong>تنبيهات:</strong><ul class="mb-0">@foreach($warnings as $warning)<li>{{ $warning }}</li>@endforeach</ul></div>@endif
<div class="restore-grid mt-4">
    <div class="card restore-card {{ count($sqlFiles) === 0 ? 'disabled-card' : '' }}"><h3>استعادة قاعدة البيانات</h3><p>تستبدل بيانات الأرشيف الحالية بالبيانات الموجودة داخل ملف SQL. المستخدمون وكلمات المرور والصلاحيات لا يتم تغييرها.</p>@if(count($sqlFiles) > 0)@if(auth()->user()?->hasPermission('backups.restore'))<form method="POST" action="{{ route('backups.restore.database', $fileName) }}" data-restore-guard onsubmit="return confirm('تأكيد نهائي: هل تريد استعادة قاعدة البيانات؟')">@csrf @include('backups.restore-confirm-fields')<button type="submit" class="btn btn-danger" disabled data-restore-submit>استعادة قاعدة البيانات</button></form>@endif @else <div class="alert alert-warning">لا يوجد ملف SQL داخل هذه النسخة.</div>@endif</div>
    <div class="card restore-card {{ $documentFilesCount === 0 ? 'disabled-card' : '' }}"><h3>استعادة ملفات المرفقات</h3><p>تستبدل مجلد المرفقات الحالي بمجلد <strong>documents</strong> الموجود داخل النسخة. سيتم حفظ نسخة أمان من الملفات الحالية أولاً.</p>@if($documentFilesCount > 0)@if(auth()->user()?->hasPermission('backups.restore'))<form method="POST" action="{{ route('backups.restore.files', $fileName) }}" data-restore-guard onsubmit="return confirm('تأكيد نهائي: هل تريد استعادة ملفات المرفقات؟')">@csrf @include('backups.restore-confirm-fields')<button type="submit" class="btn btn-danger" disabled data-restore-submit>استعادة ملفات المرفقات</button></form>@endif @else <div class="alert alert-warning">لا توجد ملفات مرفقات داخل هذه النسخة.</div>@endif</div>
    <div class="card restore-card {{ count($sqlFiles) === 0 || $documentFilesCount === 0 ? 'disabled-card' : '' }}"><h3>استعادة نسخة كاملة</h3><p>تستعيد بيانات الأرشيف وملفات المرفقات معاً. استخدم هذا الخيار للنسخ الكاملة فقط.</p>@if(count($sqlFiles) > 0 && $documentFilesCount > 0)@if(auth()->user()?->hasPermission('backups.restore'))<form method="POST" action="{{ route('backups.restore.full', $fileName) }}" data-restore-guard onsubmit="return confirm('تأكيد نهائي: هل تريد استعادة النسخة الكاملة؟')">@csrf @include('backups.restore-confirm-fields')<button type="submit" class="btn btn-danger" disabled data-restore-submit>استعادة النسخة الكاملة</button></form>@endif @else <div class="alert alert-warning">هذه النسخة لا تحتوي على قاعدة بيانات ومرفقات معاً.</div>@endif</div>
</div>
<style>.page-actions{display:flex;gap:8px;flex-wrap:wrap}.restore-summary{padding:20px}.restore-summary h3{text-align:left;margin-bottom:16px}.restore-stats-grid,.restore-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.stat-box{border:1px solid rgba(148,163,184,.25);border-radius:14px;padding:14px;background:rgba(248,250,252,.08)}.stat-box span{display:block;color:#64748b;font-size:13px;margin-bottom:8px}.restore-card{padding:18px}.restore-card p{color:#64748b;min-height:84px}.restore-confirm-panel{border:1px dashed rgba(239,68,68,.35);border-radius:14px;padding:12px;margin:12px 0;background:rgba(239,68,68,.05)}.restore-check-row{display:flex;gap:8px;align-items:flex-start;margin:0 0 10px;cursor:pointer}.restore-check-row input{margin-top:5px}.restore-confirm-label{display:block;margin-bottom:6px;font-weight:700}.disabled-card{opacity:.75}</style>
<script>document.querySelectorAll('[data-restore-guard]').forEach(function(form){const checkbox=form.querySelector('[data-restore-checkbox]');const text=form.querySelector('[data-restore-text]');const submit=form.querySelector('[data-restore-submit]');function update(){const ok=checkbox&&checkbox.checked&&text&&text.value.trim()==='استعادة';if(submit)submit.disabled=!ok;}if(checkbox)checkbox.addEventListener('change',update);if(text)text.addEventListener('input',update);update();});</script>
@endsection
