<?php

/**
 * QR print-only cleanup fix for DocumentArchive.
 * - Prevents print-position QR from appearing/floating inside the normal document show page.
 * - Provides a single shared print-position partial for print pages.
 * - Loads a small CSS/JS cleanup layer safely.
 */

$root = realpath(__DIR__ . '/..');
if (!$root || !file_exists($root . DIRECTORY_SEPARATOR . 'artisan')) {
    fwrite(STDERR, "ERROR: شغّل السكربت من جذر مشروع Laravel: php scripts/apply_qr_print_only_cleanup_fix.php\n");
    exit(1);
}

function writeFileEnsured(string $path, string $content): void {
    $dir = dirname($path);
    if (!is_dir($dir)) {
        mkdir($dir, 0777, true);
    }
    file_put_contents($path, $content);
}

function removeBackupDirs(string $base): void {
    if (!is_dir($base)) return;
    $it = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($base, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST
    );
    foreach ($it as $item) {
        if ($item->isDir() && str_starts_with($item->getFilename(), '_backup')) {
            $dir = $item->getPathname();
            $rit = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS),
                RecursiveIteratorIterator::CHILD_FIRST
            );
            foreach ($rit as $sub) {
                $sub->isDir() ? @rmdir($sub->getPathname()) : @unlink($sub->getPathname());
            }
            @rmdir($dir);
        }
    }
}

function injectOnce(string $file, string $needle, string $insert, string $fallbackAppend = ''): bool {
    if (!file_exists($file)) return false;
    $content = file_get_contents($file);
    if (str_contains($content, $insert) || str_contains($content, trim($insert))) return true;
    if (str_contains($content, $needle)) {
        $content = str_replace($needle, $insert . "\n" . $needle, $content);
        file_put_contents($file, $content);
        return true;
    }
    if ($fallbackAppend !== '') {
        file_put_contents($file, $content . "\n" . $fallbackAppend . "\n");
        return true;
    }
    return false;
}

function findPrintBlades(string $root): array {
    $dir = $root . DIRECTORY_SEPARATOR . 'resources' . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR . 'documents';
    if (!is_dir($dir)) return [];
    $files = [];
    $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS));
    foreach ($it as $file) {
        if (!$file->isFile()) continue;
        $path = $file->getPathname();
        $name = strtolower($file->getFilename());
        $rel = str_replace($root . DIRECTORY_SEPARATOR, '', $path);
        if (str_contains($rel, '_backup')) continue;
        if (str_ends_with($name, '.blade.php') && (str_contains($name, 'print') || str_contains($name, 'reference'))) {
            $files[] = $path;
        }
    }
    return $files;
}

removeBackupDirs($root . DIRECTORY_SEPARATOR . 'app');
removeBackupDirs($root . DIRECTORY_SEPARATOR . 'resources');
removeBackupDirs($root . DIRECTORY_SEPARATOR . 'routes');

$css = <<<'CSS'
/* QR cleanup and print positioning - generated by apply_qr_print_only_cleanup_fix.php */
.da-qr-print-fixed {
    position: absolute !important;
    z-index: 20;
    box-sizing: border-box;
    text-align: center;
    direction: rtl;
    background: #fff;
    border: 0.25mm solid #d9dee8;
    border-radius: 1.5mm;
    line-height: 1.15;
    overflow: hidden;
}
.da-qr-print-fixed img,
.da-qr-print-fixed svg {
    display: block;
    width: 100% !important;
    height: auto !important;
    margin: 0 auto;
}
.da-qr-print-label {
    display: block;
    color: #6b7280;
    white-space: nowrap;
    margin-top: 1mm;
}
@media print {
    .da-qr-print-fixed {
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
    }
}
CSS;
writeFileEnsured($root . '/public/css/document-qr-print-only-cleanup.css', $css);

$js = <<<'JS'
(function () {
    function closestBox(el) {
        return el.closest('.da-qr-print-fixed, .da-print-qr, .document-print-qr, .document-qr-card, .qr-print-card, .qr-card, .da-qr-card, .card, .panel, div') || el;
    }

    function cleanupNormalShowPage() {
        var path = window.location.pathname || '';
        var isDocumentShow = /^\/documents\/\d+\/?$/.test(path);
        if (!isDocumentShow) return;

        document.body.classList.add('da-document-show-page');

        var selectors = [
            '.da-qr-print-fixed',
            '.da-print-qr',
            '.document-print-qr',
            '.qr-print-card',
            '.document-qr-card',
            '[data-da-print-qr="1"]',
            'img[src*="/qr.svg"]',
            'img[src*="qr.svg"]',
            'iframe[src*="/qr.svg"]'
        ];

        var nodes = [];
        selectors.forEach(function (sel) {
            document.querySelectorAll(sel).forEach(function (node) {
                if (nodes.indexOf(node) === -1) nodes.push(node);
            });
        });

        nodes.forEach(function (node) {
            var box = closestBox(node);
            box.classList.add('da-hidden-normal-show-qr');
            box.style.display = 'none';
        });
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', cleanupNormalShowPage);
    } else {
        cleanupNormalShowPage();
    }
})();
JS;
writeFileEnsured($root . '/public/js/document-qr-print-only-cleanup.js', $js);

$partial = <<<'BLADE'
{{-- QR print position partial - controlled from /settings/qr-print-position --}}
@php
    use Illuminate\Support\Facades\DB;
    use Illuminate\Support\Facades\Route;

    $daQrDocument = $document ?? $book ?? $documentModel ?? $item ?? null;

    $daQrSettings = [];
    try {
        if (\Illuminate\Support\Facades\Schema::hasTable('qr_print_settings')) {
            $daQrSettings = DB::table('qr_print_settings')->pluck('value', 'key')->toArray();
        }
    } catch (\Throwable $e) {
        $daQrSettings = [];
    }

    $daQrEnabled = filter_var($daQrSettings['enabled'] ?? $daQrSettings['show_qr'] ?? true, FILTER_VALIDATE_BOOLEAN);
    $daQrShowLabel = filter_var($daQrSettings['show_label'] ?? $daQrSettings['label_enabled'] ?? true, FILTER_VALIDATE_BOOLEAN);

    $daQrX = is_numeric($daQrSettings['x'] ?? null) ? (float) $daQrSettings['x'] : 55;
    $daQrY = is_numeric($daQrSettings['y'] ?? null) ? (float) $daQrSettings['y'] : 48;
    $daQrSize = is_numeric($daQrSettings['size'] ?? null) ? (float) $daQrSettings['size'] : 16;
    $daQrPadding = is_numeric($daQrSettings['padding'] ?? null) ? (float) $daQrSettings['padding'] : 1;
    $daQrLabelSize = is_numeric($daQrSettings['label_size'] ?? null) ? (float) $daQrSettings['label_size'] : 2.2;

    $daQrId = is_object($daQrDocument) ? ($daQrDocument->id ?? null) : null;
    $daQrRouteName = Route::has('documents.qr') ? 'documents.qr' : (Route::has('documents.qr.svg') ? 'documents.qr.svg' : null);
@endphp

@if($daQrEnabled && $daQrId && $daQrRouteName)
    <div class="da-qr-print-fixed" data-da-print-qr="1"
         style="left: {{ $daQrX }}mm; top: {{ $daQrY }}mm; width: {{ $daQrSize + ($daQrPadding * 2) }}mm; padding: {{ $daQrPadding }}mm;">
        <img src="{{ route($daQrRouteName, $daQrId) }}" alt="QR">
        @if($daQrShowLabel)
            <span class="da-qr-print-label" style="font-size: {{ $daQrLabelSize }}mm;">رمز الوصول الإلكتروني</span>
        @endif
    </div>
@endif
BLADE;
writeFileEnsured($root . '/resources/views/documents/partials/qr-print-position.blade.php', $partial);

// Load CSS/JS in main layout.
$layoutCandidates = [
    $root . '/resources/views/layouts/app.blade.php',
    $root . '/resources/views/layouts/admin.blade.php',
    $root . '/resources/views/layouts/main.blade.php',
];
foreach ($layoutCandidates as $layout) {
    if (!file_exists($layout)) continue;
    $link = "<link rel=\"stylesheet\" href=\"{{ asset('css/document-qr-print-only-cleanup.css') }}\">";
    $script = "<script src=\"{{ asset('js/document-qr-print-only-cleanup.js') }}\" defer></script>";
    injectOnce($layout, '</head>', $link);
    injectOnce($layout, '</body>', $script, $script);
}

// Include partial inside print-related document blade files.
$include = "@include('documents.partials.qr-print-position', ['document' => \$document ?? \$book ?? null])";
$updatedPrints = 0;
foreach (findPrintBlades($root) as $blade) {
    $content = file_get_contents($blade);
    if (str_contains($content, "documents.partials.qr-print-position")) {
        $updatedPrints++;
        continue;
    }
    if (str_contains($content, '</body>')) {
        $content = str_replace('</body>', $include . "\n</body>", $content);
    } else {
        $content .= "\n" . $include . "\n";
    }
    file_put_contents($blade, $content);
    $updatedPrints++;
}

if ($updatedPrints === 0) {
    fwrite(STDERR, "WARNING: لم يتم العثور على ملف طباعة داخل resources/views/documents يحتوي print/reference. قد تحتاج تزويدي باسم ملف الطباعة.\n");
}

echo "DONE: تم تنظيف ظهور QR في صفحة العرض وربط QR بملف جزئي خاص بالطباعة فقط. ملفات الطباعة المعدلة: {$updatedPrints}\n";
echo "NEXT: php artisan view:clear && php artisan optimize:clear && php scripts/check_qr_print_only_cleanup_fix.php\n";
